/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { InputChange, InputValidate } from "./types/input";
export namespace Components {
    interface TcInput {
        "disabled": boolean;
        "group": string;
        "label": string;
        "message": string;
        "name": string;
        "placeholder": string;
        "setValue": (value: string) => Promise<void>;
        "type": string;
    }
}
declare global {
    interface HTMLTcInputElement extends Components.TcInput, HTMLStencilElement {
    }
    var HTMLTcInputElement: {
        prototype: HTMLTcInputElement;
        new (): HTMLTcInputElement;
    };
    interface HTMLElementTagNameMap {
        "tc-input": HTMLTcInputElement;
    }
}
declare namespace LocalJSX {
    interface TcInput {
        "disabled"?: boolean;
        "group"?: string;
        "label"?: string;
        "message"?: string;
        "name"?: string;
        "onTc-input-change"?: (event: CustomEvent<InputChange>) => void;
        "onTc-input-validation"?: (event: CustomEvent<InputValidate>) => void;
        "placeholder"?: string;
        "type"?: string;
    }
    interface IntrinsicElements {
        "tc-input": TcInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tc-input": LocalJSX.TcInput & JSXBase.HTMLAttributes<HTMLTcInputElement>;
        }
    }
}
